package testing;

import java.lang.reflect.Field;

public class Publicizer {
    /**
     * This terrifying piece of code uses reflection to access private data from
     * classes.
     * 
     * It was generated by ChatGPT and should ONLY EVER BE USED FOR TESTING, and
     * even then with caution
     * 
     * @param <T>
     * @param obj       the object we want to look at
     * @param fieldName the field we want to access
     * @return the value of the field
     * @throws NoSuchFieldException
     */
    public static <T> T getField(Object obj, String fieldName) {
        Class<?> cls = obj.getClass();
        while (cls != null) {
            try {
                Field field = cls.getDeclaredField(fieldName);
                field.setAccessible(true);
                return (T) field.get(obj);
            } catch (NoSuchFieldException e) {
                cls = cls.getSuperclass();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
        System.out.println(String.format("Field %s not found", fieldName));
        return null;
    }

}
